CREATE EXTENSION IF NOT EXISTS postgis;
CREATE EXTENSION IF NOT EXISTS postgis_topology;


CREATE TABLE "discount_policy_detail" (
	"discount_policy_detail_id"	BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	"places_id"	BIGINT		NOT NULL,
	"unit_base_amount"	INT		NULL,
	"discount_value"	INT		NULL,
	"percent"	INT		NULL,
	"min_purchase_amount"	INT		NULL,
	"max_discount_amount"	INT		NULL,
	"discount_code"	VARCHAR		NULL,
	"membership_code"	VARCHAR		NULL,
	"marker_code"	VARCHAR		NULL
);

CREATE TABLE "store_owners" (
	"owner_id"	BIGINT		GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	"pos_id"	BIGINT		NOT NULL,
	"owner_name"	VARCHAR		NULL,
	"owner_email"	VARCHAR		NULL,
	"owner_password"	VARCHAR		NULL
);



CREATE TABLE "user_histories" (
	"user_histories_id"	BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	"user_id"	BIGINT		NOT NULL,
	"user_coupons_id"	BIGINT		NULL,
	"places_id"	BIGINT		NOT NULL,
	"used_at"	DATE		NULL,
	"original_amount"	INT		NULL,
	"membership_discount_amount"	INT		NULL,
	"coupon_discount_amount"	INT		NULL,
	"total_discount_amount"	INT		NULL,
	"total_payment_amount"	INT		NULL,
	"is_coupon_used"	BOOLEAN		NULL,
	"is_membership_used"	BOOLEAN		NULL,
	"paid_at"	DATE		NULL,
	"discount_code"	VARCHAR		NULL,
	"membership_code"	VARCHAR		NULL
);


CREATE TABLE "users" (
	"user_id"	BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	"name"	VARCHAR		NULL,
	"email"	VARCHAR		NULL,
	"tel"	VARCHAR		NULL,
	"password"	VARCHAR		NULL,
	"birthdate"	DATE		NULL,
	"membership_code"	VARCHAR		NULL,
	"gender"	VARCHAR		NULL,
	"created_at"	DATE		NULL,
	"updated_at"	DATE		NULL,
	"is_profile_complete"	BOOLEAN		NULL,
	"barcode_number"	VARCHAR		NULL
);




CREATE TABLE "unear_events" (
	"unear_events_id"	BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	"coupon_templates_id"	BIGINT		NULL,
	"event_name"	VARCHAR		NULL,
	"event_description"	VARCHAR		NULL,
	"latitude"	NUMERIC(10, 7)		NULL,
	"longitude"	NUMERIC(10, 7)		NULL,
	"radius_meter"	NUMERIC(10, 7)		NULL,
	"start_at"	DATE		NULL,
	"end_at"	DATE		NULL
);


CREATE TABLE "pos" (
	"pos_id"	BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	"places_id"	BIGINT		NOT NULL
);


CREATE TABLE "commoncode" (
	"groupcode_id"	VARCHAR		NOT NULL,
	"coomoncode_id"	VARCHAR		NOT NULL,
	"code_desc"	VARCHAR		NULL
);


CREATE TABLE "stamps" (
	"stamps_id"	BIGINT	GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	"user_id"	BIGINT		NOT NULL,
	"event_places_id"	BIGINT		NOT NULL,
	"stamped_at"	DATE		NULL,
	"event_code"	VARCHAR		NULL,
	"place_name"	VARCHAR		NULL
);


CREATE TABLE "roulette_results" (
	"roulette_results_id"	BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	"unear_events_id"	BIGINT		NOT NULL,
	"user_id"	BIGINT		NOT NULL,
	"reward"	VARCHAR		NULL,
	"participated"	BOOLEAN		NULL
);


CREATE TABLE "places" (
	"places_id"	BIGINT		NOT NULL,
	"place_name"	VARCHAR		NULL,
	"place_desc"	VARCHAR(255)		NULL,
	"address"	VARCHAR		NULL,
	"latitude"	NUMERIC(10, 7)		NULL,
	"longitude"	NUMERIC(10, 7)		NULL,
	"benefit_category"	VARCHAR		NULL,
	"start_time"	INT		NULL,
	"end_time"	INT		NULL,
	"category_code"	VARCHAR		NULL,
	"marker_code"	VARCHAR		NULL,
	"event_code"	VARCHAR		NULL,
	"franchise_id"	BIGINT		NULL
);


CREATE TABLE "coupon_templates" (
	"coupon_templates_id"	BIGINT	GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	"discount_policy_detail_id"	BIGINT		NULL,
	"coupon_name"	VARCHAR		NULL,
	"coupon_desc"	VARCHAR		NULL,
	"remaining_quantity"	INT		NULL,
	"coupon_start"	DATE		NULL,
	"coupon_end"	DATE		NULL,
	"discount_code"	VARCHAR		NULL,
	"membership_code"	VARCHAR		NULL
);



CREATE TABLE "user_coupons" (
	"user_coupons_id"	BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	"user_id"	BIGINT		NOT NULL,
	"coupon_templates_id"	BIGINT		NOT NULL,
	"coupon_status_code"	VARCHAR		NULL,
	"barcode_number"	VARCHAR		NULL
);


CREATE TABLE "admins" (
	"admin_id"	BIGINT	GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	"admin_name"	VARCHAR		NULL,
	"admin_email"	VARCHAR		NULL,
	"admin_password"	VARCHAR		NULL
);


CREATE TABLE "franchise" (
	"franchise_id"	BIGINT	GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	"franchise_name"	VARCHAR		NULL,
	"image_url"	VARCHAR		NULL,
	`vvip_policy`	VARCHAR	NULL,
	`vip_policy`	VARCHAR	NULL,
	`basic_policy`	VARCHAR	NULL
);

CREATE TABLE "favorite_places" (
	"favorite_places_id"	BIGINT	GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	"places_id"	BIGINT		NOT NULL,
	"user_id"	BIGINT		NOT NULL,
	"created_at"	DATE		NULL,
	"deleted_at"	DATE		NULL,
	"is_favorited"	BOOLEAN		NULL
);


CREATE TABLE "pos_histories" (
	"pos_histories_id"	BIGINT	GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	"pos_id"	BIGINT		NOT NULL,
	"user_histories_id"	BIGINT		NOT NULL
);


CREATE TABLE "event_places" (
	"event_places_id"	BIGINT	GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	"unear_events_id"	BIGINT		NOT NULL,
	"places_id"	BIGINT		NOT NULL,
	"event_code"	VARCHAR		NULL
);

ALTER TABLE "discount_policy_detail" ADD CONSTRAINT "FK_places_TO_discount_policy_detail_1" FOREIGN KEY (
	"places_id"
)
REFERENCES "places" (
	"places_id"
);

ALTER TABLE "store_owners" ADD CONSTRAINT "FK_pos_TO_store_owners_1" FOREIGN KEY (
	"pos_id"
)
REFERENCES "pos" (
	"pos_id"
);

ALTER TABLE "user_histories" ADD CONSTRAINT "FK_users_TO_user_histories_1" FOREIGN KEY (
	"user_id"
)
REFERENCES "users" (
	"user_id"
);

ALTER TABLE "user_histories" ADD CONSTRAINT "FK_user_coupons_TO_user_histories_1" FOREIGN KEY (
	"user_coupons_id"
)
REFERENCES "user_coupons" (
	"user_coupons_id"
);

ALTER TABLE "user_histories" ADD CONSTRAINT "FK_places_TO_user_histories_1" FOREIGN KEY (
	"places_id"
)
REFERENCES "places" (
	"places_id"
);

ALTER TABLE "pos" ADD CONSTRAINT "FK_places_TO_pos_1" FOREIGN KEY (
	"places_id"
)
REFERENCES "places" (
	"places_id"
);

ALTER TABLE "stamps" ADD CONSTRAINT "FK_users_TO_stamps_1" FOREIGN KEY (
	"user_id"
)
REFERENCES "users" (
	"user_id"
);

ALTER TABLE "stamps" ADD CONSTRAINT "FK_event_places_TO_stamps_1" FOREIGN KEY (
	"event_places_id"
)
REFERENCES "event_places" (
	"event_places_id"
);

ALTER TABLE "roulette_results" ADD CONSTRAINT "FK_unear_events_TO_roulette_results_1" FOREIGN KEY (
	"unear_events_id"
)
REFERENCES "unear_events" (
	"unear_events_id"
);

ALTER TABLE "roulette_results" ADD CONSTRAINT "FK_users_TO_roulette_results_1" FOREIGN KEY (
	"user_id"
)
REFERENCES "users" (
	"user_id"
);

ALTER TABLE "places" ADD CONSTRAINT "FK_franchise_TO_places_1" FOREIGN KEY (
	"franchise_id"
)
REFERENCES "franchise" (
	"franchise_id"
);


ALTER TABLE "user_coupons" ADD CONSTRAINT "FK_users_TO_user_coupons_1" FOREIGN KEY (
	"user_id"
)
REFERENCES "users" (
	"user_id"
);

ALTER TABLE "user_coupons" ADD CONSTRAINT "FK_coupon_templates_TO_user_coupons_1" FOREIGN KEY (
	"coupon_templates_id"
)
REFERENCES "coupon_templates" (
	"coupon_templates_id"
);

ALTER TABLE "favorite_places" ADD CONSTRAINT "FK_places_TO_favorite_places_1" FOREIGN KEY (
	"places_id"
)
REFERENCES "places" (
	"places_id"
);

ALTER TABLE "favorite_places" ADD CONSTRAINT "FK_users_TO_favorite_places_1" FOREIGN KEY (
	"user_id"
)
REFERENCES "users" (
	"user_id"
);

ALTER TABLE "pos_histories" ADD CONSTRAINT "FK_pos_TO_pos_histories_1" FOREIGN KEY (
	"pos_id"
)
REFERENCES "pos" (
	"pos_id"
);

ALTER TABLE "pos_histories" ADD CONSTRAINT "FK_user_histories_TO_pos_histories_1" FOREIGN KEY (
	"user_histories_id"
)
REFERENCES "user_histories" (
	"user_histories_id"
);

ALTER TABLE "event_places" ADD CONSTRAINT "FK_unear_events_TO_event_places_1" FOREIGN KEY (
	"unear_events_id"
)
REFERENCES "unear_events" (
	"unear_events_id"
);

ALTER TABLE "event_places" ADD CONSTRAINT "FK_places_TO_event_places_1" FOREIGN KEY (
	"places_id"
)
REFERENCES "places" (
	"places_id"
);



 
-- 더미데이터
INSERT INTO users (
  user_id, name, email, tel, password, birthdate, membership_code, gender, created_at, updated_at
) VALUES (
  1, '홍길동1', 'user1@test.com', '01012345678',
  '$2a$10$UOg9Y/WOYuFpLSqAAXUHKukkCGsMUVT3BQ4hEBKNT9jZMml4Jv1O.', -- pw1
  '1990-01-01', 'VIP', 'M', NOW(), NOW()
);


INSERT INTO franchise (franchise_name, image_url) VALUES
('GS25', 'https://your-cdn.com/images/gs25-logo.png'),
('CU', 'https://your-cdn.com/images/cu-logo.png');

INSERT INTO places (
    franchise_id, place_name, address, business_hours, latitude, longitude, 
    marker_code, event_code, category_code, place_desc
) VALUES
-- GS25 강남점
(1, 'GS25 강남점', '서울특별시 강남구 테헤란로 1', '24시간', 37.4980950, 127.0276100, 'MARKER_GS25', 'EVT001', 'CATEGORY_CONV', 'GS25 강남역점입니다.'),
-- CU 신촌점
(2, 'CU 신촌점', '서울특별시 서대문구 연세로 10', '24시간', 37.5600000, 126.9368000, 'MARKER_CU', 'EVT002', 'CATEGORY_CONV', 'CU 신촌점입니다.'),
-- 일반 비프랜차이즈 장소
(NULL, '홍대 팝업스토어', '서울특별시 마포구 어울마당로 35', '10:00~22:00', 37.5563000, 126.9235000, 'MARKER_EVENT', 'EVT_POPUP', 'CATEGORY_ETC', '홍대 팝업입니다.');

INSERT INTO discount_policy_detail (
    places_id, unit_base_amount, discount_value, percent,
    min_purchase_amount, max_discount_amount,
    discount_code, membership_code, marker_code
) VALUES
-- GS25 강남점: 정액 1000원 할인
(1, 0, 1000, NULL, 5000, 1000, 'DISC_FIXED_1000', 'VIP', 'MARKER_GS25'),

-- CU 신촌점: 10% 할인, 최대 2,000원
(2, 0, NULL, 10, 7000, 2000, 'DISC_PERCENT_10', 'VVIP', 'MARKER_CU'),

(3, 0, 2000, NULL, 8000, 2000, 'DISC_PERCENT_20', 'VIP', 'MARKER_EVENT'),

-- 홍대 팝업: 고정 2,000원 할인, VIP 대상
(4, 0, 2000, NULL, 8000, 2000, 'DISC_POPUP_2000', 'VIP', 'MARKER_EVENT');
